import { useEffect, useState, type ComponentType } from 'react';
import { motion } from 'framer-motion';
import {
  Download,
  Flag,
  CreditCard,
  Mail,
  MapPinned,
  Printer,
  ScanLine,
  ShieldCheck,
  Ticket,
  UserRound,
  Wallet,
} from 'lucide-react';
import { PageHeader } from '@/components/shared/PageHeader';
import { LoadingSpinner } from '@/components/shared/LoadingSpinner';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { formatDate } from '@/lib/utils';
import api from '@/lib/api';
import { useAuth } from '@/features/auth/AuthContext';

type PassData = {
  ticketNumber: string | null;
  registrationNumber: string;
  registrationStatus: string;
  paymentStatus: string;
  assignedCommittee: string | null;
  committeeAbbr: string | null;
  assignedCountry: string | null;
  submittedAt: string;
  // Real base64 QR data URL generated by the backend worker after payment
  // verification. null means payment is not yet verified or QR is still
  // being generated. The raw qrToken is never sent to the frontend.
  qrCode: string | null;
  ticketStatus: string | null;
};

// ── Three explicit pass states ────────────────────────────────────────────────
// 'pending'    – paymentStatus !== 'paid'
// 'waitlisted' – paid but committee was full at capture; ops will resolve
// 'generating' – paymentStatus === 'paid' but qrCode not yet ready
// 'ready'      – paymentStatus === 'paid' AND qrCode is a real data URL
type PassState = 'pending' | 'waitlisted' | 'generating' | 'ready';

function derivePassState(data: PassData | null): PassState {
  if (!data || data.paymentStatus !== 'paid') return 'pending';
  if (data.registrationStatus === 'waitlisted') return 'waitlisted';
  if (!data.qrCode) return 'generating';
  return 'ready';
}

type PassStatus = 'valid' | 'pending' | 'used' | 'expired';

function usePassData(authLoading: boolean, isAuthenticated: boolean, userId?: string) {
  const [data, setData] = useState<PassData | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchPass = (signal: AbortSignal) =>
    api
      .get<{ data: PassData }>(`/delegates/pass?t=${Date.now()}`, {
        signal,
        headers: { 'Cache-Control': 'no-cache', Pragma: 'no-cache' },
      })
      .then((res) => res.data.data)
      .catch((err) => {
        if (err.name !== 'CanceledError') throw err;
        return null;
      });

  useEffect(() => {
    if (authLoading) return;
    if (!isAuthenticated || !userId) {
      setData(null);
      setLoading(false);
      return;
    }

    const controller = new AbortController();
    setData(null);
    setLoading(true);

    fetchPass(controller.signal)
      .then((d) => {
        if (!controller.signal.aborted) setData(d);
      })
      .catch(() => {
        if (!controller.signal.aborted) setData(null);
      })
      .finally(() => {
        if (!controller.signal.aborted) setLoading(false);
      });

    return () => controller.abort();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [authLoading, isAuthenticated, userId]);

  // Poll every 3 s while the QR is still being generated so the page
  // automatically transitions to 'ready' without any user action.
  // Does NOT run for 'waitlisted' — no QR will ever arrive in that state.
  useEffect(() => {
    if (loading) return;
    if (derivePassState(data) !== 'generating') return;

    const controller = new AbortController();
    const id = window.setInterval(() => {
      fetchPass(controller.signal)
        .then((d) => {
          if (d && !controller.signal.aborted) setData(d);
        })
        .catch(() => {});
    }, 3_000);

    return () => {
      clearInterval(id);
      controller.abort();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, data]);

  return { data, loading: authLoading || loading };
}

function getPassStatus(passData: PassData | null): PassStatus {
  if (!passData?.ticketNumber) return 'pending';
  if (passData.paymentStatus !== 'paid') return 'pending';
  if (passData.ticketStatus === 'used') return 'used';
  if (passData.ticketStatus === 'cancelled' || passData.ticketStatus === 'revoked')
    return 'expired';
  return 'valid';
}

const passStatusConfig: Record<
  PassStatus,
  { label: string; variant: 'active' | 'pending' | 'inactive' | 'urgent' }
> = {
  valid: { label: 'Verified', variant: 'active' },
  pending: { label: 'Pending', variant: 'pending' },
  used: { label: 'Used', variant: 'inactive' },
  expired: { label: 'Expired', variant: 'urgent' },
};

function PassSkeleton() {
  return (
    <Card className="overflow-hidden border-white/[0.08] bg-[#09131f] text-white shadow-2xl shadow-black/30">
      <CardHeader className="border-b border-white/10 bg-white/[0.02]">
        <div className="flex items-center gap-4">
          <div className="flex h-14 w-14 items-center justify-center rounded-2xl border border-gold-500/30 bg-gold-500/10 text-gold-300">
            <LoadingSpinner size="sm" />
          </div>
          <div className="space-y-2">
            <div className="h-4 w-40 rounded-full bg-white/10" />
            <div className="h-3 w-72 rounded-full bg-white/5" />
          </div>
        </div>
      </CardHeader>
      <CardContent className="grid gap-6 p-6 lg:grid-cols-[1.2fr_0.8fr]">
        <div className="space-y-4">
          <div className="h-4 w-24 rounded-full bg-white/10" />
          <div className="h-14 w-full rounded-2xl bg-white/5" />
          <div className="h-14 w-full rounded-2xl bg-white/5" />
          <div className="h-14 w-full rounded-2xl bg-white/5" />
        </div>
        <div className="rounded-[28px] border border-white/10 bg-[#f7f2e8] p-5">
          <div className="h-[360px] rounded-[24px] bg-white shadow-inner" />
        </div>
      </CardContent>
    </Card>
  );
}

function AllocationField({
  label,
  value,
  icon: Icon,
}: {
  label: string;
  value: string;
  icon: ComponentType<{ className?: string }>;
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
      <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.3em] text-muted-foreground">
        <Icon className="h-3.5 w-3.5 text-gold-400" />
        {label}
      </div>
      <p className="mt-3 text-sm font-medium text-foreground">{value}</p>
    </div>
  );
}

export default function DelegatePass() {
  const { user, isAuthenticated, isLoading: authLoading } = useAuth();
  const { data: passData, loading } = usePassData(authLoading, isAuthenticated, user?.id);
  const [isDownloading, setIsDownloading] = useState(false);

  const passState = derivePassState(passData);
  const isReady = passState === 'ready';

  const ticket = isReady ? (passData!.ticketNumber ?? 'Pending') : 'Pending';
  const country = isReady
    ? (passData!.assignedCountry ?? 'Pending assignment')
    : 'Pending assignment';
  const committee = isReady
    ? (passData!.assignedCommittee ?? 'Awaiting committee')
    : 'Awaiting committee';
  const delegateName = user?.email ?? 'Delegate';
  const allocationDate = passData?.submittedAt ?? new Date().toISOString();
  const qrCode = isReady ? passData!.qrCode! : null;

  const passStatus = getPassStatus(passData);
  const statusConfig = passStatusConfig[passStatus];

  const handlePrint = () => window.print();

  const handleDownload = async () => {
    if (!isReady || !qrCode) return;
    setIsDownloading(true);
    try {
      const svg = buildPassSvg();
      const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const img = new Image();

      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = 1400;
        canvas.height = 900;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          URL.revokeObjectURL(url);
          setIsDownloading(false);
          return;
        }
        ctx.drawImage(img, 0, 0, 1400, 900);
        canvas.toBlob((pngBlob) => {
          if (!pngBlob) {
            URL.revokeObjectURL(url);
            setIsDownloading(false);
            return;
          }
          const dl = URL.createObjectURL(pngBlob);
          const a = document.createElement('a');
          a.href = dl;
          a.download = `${ticket}.png`;
          a.click();
          URL.revokeObjectURL(dl);
          URL.revokeObjectURL(url);
          setIsDownloading(false);
        }, 'image/png');
      };
      img.onerror = () => {
        URL.revokeObjectURL(url);
        const dl = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = dl;
        a.download = `${ticket}.svg`;
        a.click();
        URL.revokeObjectURL(dl);
        setIsDownloading(false);
      };
      img.src = url;
    } catch {
      setIsDownloading(false);
    }
  };

  function buildPassSvg() {
    // qrCode is the real base64 data URL from the backend — used directly as
    // the <image> href so the downloaded pass contains the authentic QR code.
    return `<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="900" viewBox="0 0 1400 900">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#07111f"/>
      <stop offset="60%" stop-color="#0d1b2d"/>
      <stop offset="100%" stop-color="#15243a"/>
    </linearGradient>
  </defs>
  <rect width="1400" height="900" rx="40" fill="url(#bg)"/>
  <rect x="48" y="48" width="1304" height="804" rx="34" fill="#f5efe2" opacity="0.98"/>
  <rect x="72" y="72" width="1256" height="756" rx="28" fill="#ffffff"/>
  <rect x="72" y="72" width="1256" height="126" rx="28" fill="#09131f"/>
  <rect x="72" y="180" width="1256" height="648" rx="0" fill="#ffffff"/>
  <rect x="72" y="180" width="1256" height="10" fill="#d4af37"/>
  <text x="114" y="122" fill="#f8f4ea" font-family="Inter, Arial, sans-serif" font-size="26" letter-spacing="6">DELEGATE PASS</text>
  <text x="114" y="157" fill="#d4af37" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="3">MUN GRIDIXIA CONFERENCE ACCESS</text>
  <text x="114" y="268" fill="#07111f" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="3">DELEGATE NAME</text>
  <text x="114" y="320" fill="#07111f" font-family="Georgia, serif" font-size="54" font-weight="700">${escapeXml(delegateName)}</text>
  <text x="114" y="386" fill="#6b7280" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="3">COMMITTEE</text>
  <text x="114" y="426" fill="#07111f" font-family="Inter, Arial, sans-serif" font-size="34" font-weight="700">${escapeXml(committee)}</text>
  <text x="114" y="488" fill="#6b7280" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="3">COUNTRY</text>
  <text x="114" y="528" fill="#07111f" font-family="Inter, Arial, sans-serif" font-size="34" font-weight="700">${escapeXml(country)}</text>
  <text x="114" y="618" fill="#6b7280" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="3">TICKET NUMBER</text>
  <text x="114" y="660" fill="#07111f" font-family="Inter, Arial, sans-serif" font-size="32" font-weight="700">${escapeXml(ticket)}</text>
  <text x="114" y="736" fill="#6b7280" font-family="Inter, Arial, sans-serif" font-size="16" letter-spacing="2">ALLOCATION DATE</text>
  <text x="114" y="770" fill="#07111f" font-family="Inter, Arial, sans-serif" font-size="24" font-weight="600">${escapeXml(formatDate(allocationDate))}</text>
  <rect x="796" y="232" width="492" height="492" rx="30" fill="#faf7f0" stroke="#eadfc4" stroke-width="2"/>
  <image x="846" y="282" width="392" height="392" href="${qrCode}"/>
  <text x="1042" y="744" fill="#6b7280" text-anchor="middle" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="2">SCAN TO VERIFY</text>
  <rect x="796" y="760" width="492" height="72" rx="18" fill="#f4ead1"/>
  <text x="1042" y="804" fill="#07111f" text-anchor="middle" font-family="Inter, Arial, sans-serif" font-size="18" font-weight="600">ISSUED BY MUN GRIDIXIA OPERATIONS</text>
</svg>`;
  }

  if (loading) {
    return (
      <div className="space-y-6">
        <PageHeader title="Delegate Pass" subtitle="Conference access pass with QR verification" />
        <PassSkeleton />
      </div>
    );
  }

  // State: waitlisted — payment received but committee was full at capture.
  if (passState === 'waitlisted') {
    return (
      <div className="space-y-6">
        <PageHeader title="Delegate Pass" subtitle="Conference access pass with QR verification" />
        <Card className="border-amber-500/20 bg-amber-500/10">
          <CardContent className="flex flex-col items-center gap-5 py-16 text-center">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl border border-amber-500/30 bg-amber-500/10">
              <Ticket className="h-7 w-7 text-amber-400" />
            </div>
            <div className="space-y-2">
              <p className="text-base font-semibold text-foreground">
                Your payment has been received successfully.
              </p>
              <p className="text-sm text-muted-foreground max-w-sm">
                Unfortunately, the selected committee reached full capacity before your seat could
                be confirmed. Your registration has been placed on the waitlist. Our organizing team
                will contact you regarding an alternate committee or a full refund.
              </p>
            </div>
            <Badge variant="pending">Waitlisted</Badge>
          </CardContent>
        </Card>
      </div>
    );
  }

  // State 2 – Payment verified, QR worker still running.
  // Poll is active in usePassData; this screen auto-advances to State 3.
  if (passState === 'generating') {
    return (
      <div className="space-y-6">
        <PageHeader title="Delegate Pass" subtitle="Conference access pass with QR verification" />
        <Card className="glass-card border-white/[0.08]">
          <CardContent className="flex flex-col items-center gap-5 py-16 text-center">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl border border-gold-500/30 bg-gold-500/10">
              <LoadingSpinner size="sm" />
            </div>
            <div className="space-y-2">
              <p className="text-base font-semibold text-foreground">
                Payment verified successfully.
              </p>
              <p className="text-sm text-muted-foreground max-w-sm">
                Your Delegate Pass is being prepared. Please wait a few seconds…
              </p>
            </div>
            <Badge variant="active">Payment Verified</Badge>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6 pb-8">
      <PageHeader
        title="Delegate Pass"
        subtitle="Conference entry pass with scannable QR code and wallet integration"
        actions={
          <div className="flex flex-wrap items-center gap-2 print:hidden">
            <Button
              size="sm"
              variant="outline"
              onClick={handleDownload}
              disabled={!isReady || isDownloading}
            >
              <Download size={14} />
              {isDownloading ? 'Exporting…' : 'Download'}
            </Button>
            <Button size="sm" variant="outline" onClick={handlePrint} disabled={!isReady}>
              <Printer size={14} />
              Print
            </Button>
            <Button size="sm" asChild>
              <a href="/country-allocation">View Allocation</a>
            </Button>
          </div>
        }
      />

      <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 items-start w-full">
        <motion.div
          className="xl:col-span-7"
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.25 }}
        >
          <div className="bg-navy-900/50 border border-white/[0.05] rounded-2xl p-6 text-white">
            <div className="flex flex-wrap items-start justify-between gap-4 border-b border-white/10 pb-5">
              <div>
                <p className="text-[10px] uppercase tracking-[0.36em] text-white/50">
                  Delegate Access
                </p>
                <h2 className="mt-2 text-2xl font-semibold text-white">Conference Entry Card</h2>
                <p className="mt-2 max-w-xl text-sm text-white/65">
                  Present this pass at check-in. It keeps your delegate identity, committee
                  assignment, and QR verification in one polished view.
                </p>
              </div>
              <div className="rounded-2xl border border-gold-500/20 bg-gold-500/10 px-4 py-3 text-right">
                <p className="text-[10px] uppercase tracking-[0.32em] text-gold-300">
                  Ticket Number
                </p>
                <p className="mt-1 text-xl font-semibold text-gold-200">{ticket}</p>
              </div>
            </div>

            <div className="mt-5 space-y-5">
              <div className="flex flex-wrap items-center gap-2">
                <Badge variant={statusConfig.variant}>{statusConfig.label}</Badge>
                <Badge variant="default">Conference Entry</Badge>
              </div>

              <div className="space-y-4 rounded-[28px] border border-white/10 bg-gradient-to-br from-white/[0.05] via-white/[0.03] to-gold-500/[0.06] p-5 shadow-[0_24px_60px_rgba(0,0,0,0.26)]">
                <div className="flex items-start gap-4">
                  <div className="flex h-16 w-16 items-center justify-center rounded-3xl border border-gold-500/20 bg-gold-500/10 text-3xl shadow-inner shadow-gold-500/10">
                    {isReady ? '🏛️' : '🏳️'}
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-[10px] uppercase tracking-[0.3em] text-white/60">Delegate</p>
                    <h3 className="mt-2 truncate text-3xl font-semibold text-white sm:text-4xl">
                      {delegateName}
                    </h3>
                    <div className="mt-3 flex flex-wrap items-center gap-2">
                      <Badge variant="mun">Professional Conference</Badge>
                      <Badge variant={isReady ? 'active' : 'pending'}>
                        {isReady ? 'Payment Verified' : 'Payment Pending'}
                      </Badge>
                    </div>
                  </div>
                </div>

                <div className="grid gap-3 sm:grid-cols-2">
                  <AllocationField label="Committee" value={committee} icon={MapPinned} />
                  <AllocationField label="Country" value={country} icon={Flag} />
                  <AllocationField label="Ticket Number" value={ticket} icon={Ticket} />
                  <AllocationField
                    label="Allocation Date"
                    value={formatDate(allocationDate)}
                    icon={CreditCard}
                  />
                </div>
              </div>

              <div className="grid gap-3 sm:grid-cols-3">
                <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                  <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.3em] text-white/60">
                    <UserRound className="h-3.5 w-3.5 text-gold-300" />
                    Delegate
                  </div>
                  <p className="mt-3 text-sm text-white">{delegateName}</p>
                </div>
                <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                  <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.3em] text-white/60">
                    <Wallet className="h-3.5 w-3.5 text-gold-300" />
                    Session
                  </div>
                  <p className="mt-3 text-sm text-white">
                    {passData?.registrationNumber || 'Pending receipt'}
                  </p>
                </div>
                <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                  <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.3em] text-white/60">
                    <ShieldCheck className="h-3.5 w-3.5 text-gold-300" />
                    Payment Status
                  </div>
                  <p className="mt-3 text-sm text-white capitalize">
                    {isReady ? 'Verified' : 'Pending'}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* QR pass card — only rendered after backend payment verification */}
        <div className="xl:col-span-5 w-full max-w-[400px] mx-auto bg-white text-neutral-900 rounded-2xl p-6 shadow-xl flex flex-col items-center">
          <div className="w-full flex items-center justify-between gap-3 mb-4">
            <div>
              <p className="text-[10px] uppercase tracking-[0.32em] text-slate-500">QR Code</p>
              <p className="mt-1 text-sm font-medium text-slate-900">
                {isReady
                  ? 'Scan at entry for verification'
                  : 'Available after payment verification'}
              </p>
            </div>
            <ScanLine className="h-5 w-5 text-slate-400" />
          </div>

          <div className="w-full flex items-center justify-center rounded-[26px] bg-[#faf7f0] p-4 min-h-[232px]">
            {isReady && qrCode ? (
              <img
                src={qrCode}
                alt="Delegate QR code"
                width={200}
                height={200}
                className="rounded"
              />
            ) : (
              <div className="flex flex-col items-center gap-3 text-center">
                <div className="flex h-16 w-16 items-center justify-center rounded-2xl border border-slate-200 bg-slate-100">
                  <ScanLine className="h-7 w-7 text-slate-300" />
                </div>
                <p className="text-xs text-slate-400 max-w-[160px]">
                  QR code will appear here once your payment is verified
                </p>
              </div>
            )}
          </div>

          <div className="mt-4 grid w-full gap-3 grid-cols-2">
            <InfoChip label="Committee" value={committee} />
            <InfoChip label="Country" value={country} />
            <InfoChip label="Ticket" value={ticket} />
            <InfoChip label="Date" value={formatDate(allocationDate)} />
          </div>
        </div>

        <div className="xl:col-span-12 space-y-4 print:hidden">
          <Card className="glass-card border-white/[0.08]">
            <CardHeader className="space-y-3 border-b border-white/[0.06] bg-white/[0.015]">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl border border-gold-500/20 bg-gold-500/10 text-gold-400">
                  <CreditCard className="h-4 w-4" />
                </div>
                <div>
                  <CardTitle className="text-base text-foreground">Pass Summary</CardTitle>
                  <CardDescription>
                    Conference-appropriate metadata for quick confirmation.
                  </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3 p-5">
              <SummaryRow label="Delegate" value={delegateName} />
              <SummaryRow label="Committee" value={committee} />
              <SummaryRow label="Country" value={country} />
              <SummaryRow label="Ticket" value={ticket} />
              <SummaryRow label="Receipt" value={passData?.registrationNumber || 'Pending'} />
              <SummaryRow label="Payment" value={isReady ? 'Verified' : 'Pending'} />
            </CardContent>
          </Card>

          <Card className="glass-card border-white/[0.08]">
            <CardHeader className="space-y-3 border-b border-white/[0.06] bg-white/[0.015]">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl border border-gold-500/20 bg-gold-500/10 text-gold-400">
                  <Wallet className="h-4 w-4" />
                </div>
                <div>
                  <CardTitle className="text-base text-foreground">Wallet & Delivery</CardTitle>
                  <CardDescription>Add to your phone wallet or receive via email.</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3 p-5">
              <Button className="w-full justify-start gap-2" variant="outline" disabled>
                <Wallet size={14} />
                Add to Apple Wallet
                <Badge variant="inactive" className="ml-auto text-[9px]">
                  Coming Soon
                </Badge>
              </Button>
              <Button className="w-full justify-start gap-2" variant="outline" disabled>
                <Wallet size={14} />
                Add to Google Wallet
                <Badge variant="inactive" className="ml-auto text-[9px]">
                  Coming Soon
                </Badge>
              </Button>
              <Button className="w-full justify-start gap-2" variant="outline" disabled>
                <Mail size={14} />
                Email Pass to Delegate
                <Badge variant="inactive" className="ml-auto text-[9px]">
                  Coming Soon
                </Badge>
              </Button>
            </CardContent>
          </Card>

          <Card className="glass-card border-white/[0.08]">
            <CardHeader className="space-y-3 border-b border-white/[0.06] bg-white/[0.015]">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl border border-gold-500/20 bg-gold-500/10 text-gold-400">
                  <Printer className="h-4 w-4" />
                </div>
                <div>
                  <CardTitle className="text-base text-foreground">Actions</CardTitle>
                  <CardDescription>Download, print, or jump back to allocation.</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3 p-5">
              <Button
                className="w-full justify-start"
                variant="outline"
                onClick={handleDownload}
                disabled={!isReady || isDownloading}
              >
                <Download size={14} />
                {isDownloading ? 'Exporting…' : 'Download Pass'}
              </Button>
              <Button
                className="w-full justify-start"
                variant="outline"
                onClick={handlePrint}
                disabled={!isReady}
              >
                <Printer size={14} />
                Print Pass
              </Button>
              <Button className="w-full justify-start" asChild>
                <a href="/country-allocation">Open Allocation View</a>
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>

      {passState === 'pending' && (
        <Card className="border-amber-500/20 bg-amber-500/10 text-amber-100 print:hidden">
          <CardContent className="flex flex-wrap items-center justify-between gap-4 p-5">
            <div>
              <p className="text-sm font-medium">Payment verification pending</p>
              <p className="mt-1 text-sm text-amber-100/75">
                Complete payment to unlock your delegate pass, QR code, and download options.
              </p>
            </div>
            <Button size="sm" variant="outline" asChild>
              <a href="/payments">Complete Payment</a>
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function escapeXml(str: string) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function SummaryRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-4 rounded-2xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-sm">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-medium text-foreground text-right">{value}</span>
    </div>
  );
}

function InfoChip({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-2xl border border-[#eadfc4] bg-white px-4 py-3 text-sm text-slate-900">
      <p className="text-[10px] uppercase tracking-[0.3em] text-slate-500">{label}</p>
      <p className="mt-1 font-medium">{value}</p>
    </div>
  );
}
